######################################################################
<<<<<<< HEAD
# Automatically generated by qmake (3.1) Tue Jan 31 10:35:02 2023
=======
# Automatically generated by qmake (3.1) Mon Jan 30 12:57:26 2023
>>>>>>> 8a71468a190c8db99da2c6521b137fd99fa8fd34
######################################################################

TEMPLATE = app
TARGET = Wallapop
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
<<<<<<< HEAD
HEADERS += dlogin.h \
           dprincipal.h \
           dregistro.h \
           producto.h \
           telefonomovil.h \
           usuario.h
FORMS += dlogin.ui dprincipal.ui dregistro.ui
SOURCES += dlogin.cpp \
           dprincipal.cpp \
           dregistro.cpp \
           main.cpp \
           producto.cpp \
           usuario.cpp
=======
HEADERS += dlogin.h dprincipal.h dregistro.h
FORMS += dlogin.ui dprincipal.ui dregistro.ui
SOURCES += dlogin.cpp dprincipal.cpp dregistro.cpp main.cpp
>>>>>>> 8a71468a190c8db99da2c6521b137fd99fa8fd34
QT += widgets
